# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a base Python image
FROM python:3.12-slim-bookworm

# Set the working directory in the container
WORKDIR /app

# Copy the pyproject.toml and uv.lock to the container
COPY pyproject.toml uv.lock /app/

# Install the project's dependencies
RUN --mount=type=cache,target=/root/.cache/pip pip install uv

# Copy the rest of the application's code
COPY src /app/src

# Ensure that the entrypoint is executable
RUN chmod +x /app/src/spotify_mcp/server.py

# Set environment variables for Spotify credentials
ENV SPOTIFY_CLIENT_ID="your-client-id"
ENV SPOTIFY_CLIENT_SECRET="your-client-secret"
ENV SPOTIFY_REDIRECT_URI="http://localhost:8888"

# Define the command to run the server
CMD ["uv", "run", "spotify-mcp"]
